title: CoCoML
description: The documentation for a concise and consistent modeling language for (mechatronic) systems and software.
theme: just-the-docs

url: https://gfse.github.io/CoCoML
heading_anchors: true

aux_links:
  Repo: https://github.com/gfse/CoCoML
